//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HRPortal.NewHrPortal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NewHrPortal_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal")]
    public partial class NewHrPortal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback changePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback createLeaveApplicationLinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback createLeaveApplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback createSafariRequestEntitlementsOperationCompleted;
        
        private System.Threading.SendOrPostCallback createSafariRequestHeaderOperationCompleted;
        
        private System.Threading.SendOrPostCallback createSafariRequestLinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback createStaffApplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback createStaffClaimApplicationLinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback createStoreRequisitionLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback createStoreRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback editLeaveApplicationLinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnGetEmployeeDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnStoreRequisitionLinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback generateP9OperationCompleted;
        
        private System.Threading.SendOrPostCallback generatePayslipOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendLeaveApplicationApprovalOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendSafariRequestApplicationApprovalOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendStaffClaimApplicationApprovalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NewHrPortal() {
            this.Url = global::HRPortal.Properties.Settings.Default.HRPortal_NewHrPortal_NewHrPortal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event changePasswordCompletedEventHandler changePasswordCompleted;
        
        /// <remarks/>
        public event createLeaveApplicationLinesCompletedEventHandler createLeaveApplicationLinesCompleted;
        
        /// <remarks/>
        public event createLeaveApplicationCompletedEventHandler createLeaveApplicationCompleted;
        
        /// <remarks/>
        public event createSafariRequestEntitlementsCompletedEventHandler createSafariRequestEntitlementsCompleted;
        
        /// <remarks/>
        public event createSafariRequestHeaderCompletedEventHandler createSafariRequestHeaderCompleted;
        
        /// <remarks/>
        public event createSafariRequestLinesCompletedEventHandler createSafariRequestLinesCompleted;
        
        /// <remarks/>
        public event createStaffApplicationCompletedEventHandler createStaffApplicationCompleted;
        
        /// <remarks/>
        public event createStaffClaimApplicationLinesCompletedEventHandler createStaffClaimApplicationLinesCompleted;
        
        /// <remarks/>
        public event createStoreRequisitionLineCompletedEventHandler createStoreRequisitionLineCompleted;
        
        /// <remarks/>
        public event createStoreRequisitionCompletedEventHandler createStoreRequisitionCompleted;
        
        /// <remarks/>
        public event editLeaveApplicationLinesCompletedEventHandler editLeaveApplicationLinesCompleted;
        
        /// <remarks/>
        public event fnGetEmployeeDetailCompletedEventHandler fnGetEmployeeDetailCompleted;
        
        /// <remarks/>
        public event fnStoreRequisitionLinesCompletedEventHandler fnStoreRequisitionLinesCompleted;
        
        /// <remarks/>
        public event generateP9CompletedEventHandler generateP9Completed;
        
        /// <remarks/>
        public event generatePayslipCompletedEventHandler generatePayslipCompleted;
        
        /// <remarks/>
        public event sendLeaveApplicationApprovalCompletedEventHandler sendLeaveApplicationApprovalCompleted;
        
        /// <remarks/>
        public event sendSafariRequestApplicationApprovalCompletedEventHandler sendSafariRequestApplicationApprovalCompleted;
        
        /// <remarks/>
        public event sendStaffClaimApplicationApprovalCompletedEventHandler sendStaffClaimApplicationApprovalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:changePassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="changePassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string changePassword(string employeeNo, string currentPassword, string newPassword, string confirmPassword) {
            object[] results = this.Invoke("changePassword", new object[] {
                        employeeNo,
                        currentPassword,
                        newPassword,
                        confirmPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void changePasswordAsync(string employeeNo, string currentPassword, string newPassword, string confirmPassword) {
            this.changePasswordAsync(employeeNo, currentPassword, newPassword, confirmPassword, null);
        }
        
        /// <remarks/>
        public void changePasswordAsync(string employeeNo, string currentPassword, string newPassword, string confirmPassword, object userState) {
            if ((this.changePasswordOperationCompleted == null)) {
                this.changePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangePasswordOperationCompleted);
            }
            this.InvokeAsync("changePassword", new object[] {
                        employeeNo,
                        currentPassword,
                        newPassword,
                        confirmPassword}, this.changePasswordOperationCompleted, userState);
        }
        
        private void OnchangePasswordOperationCompleted(object arg) {
            if ((this.changePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changePasswordCompleted(this, new changePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:createLeaveApplicationLines", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="createLeaveApplicationLines_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string createLeaveApplicationLines(string applicationNo, string leaveType, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateStart, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateEnd) {
            object[] results = this.Invoke("createLeaveApplicationLines", new object[] {
                        applicationNo,
                        leaveType,
                        dateStart,
                        dateEnd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createLeaveApplicationLinesAsync(string applicationNo, string leaveType, System.DateTime dateStart, System.DateTime dateEnd) {
            this.createLeaveApplicationLinesAsync(applicationNo, leaveType, dateStart, dateEnd, null);
        }
        
        /// <remarks/>
        public void createLeaveApplicationLinesAsync(string applicationNo, string leaveType, System.DateTime dateStart, System.DateTime dateEnd, object userState) {
            if ((this.createLeaveApplicationLinesOperationCompleted == null)) {
                this.createLeaveApplicationLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateLeaveApplicationLinesOperationCompleted);
            }
            this.InvokeAsync("createLeaveApplicationLines", new object[] {
                        applicationNo,
                        leaveType,
                        dateStart,
                        dateEnd}, this.createLeaveApplicationLinesOperationCompleted, userState);
        }
        
        private void OncreateLeaveApplicationLinesOperationCompleted(object arg) {
            if ((this.createLeaveApplicationLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createLeaveApplicationLinesCompleted(this, new createLeaveApplicationLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:createLeaveApplication", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="createLeaveApplication_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string createLeaveApplication(string applicationNo, string employeeNumber, string reliever, string contactAddress, string naration) {
            object[] results = this.Invoke("createLeaveApplication", new object[] {
                        applicationNo,
                        employeeNumber,
                        reliever,
                        contactAddress,
                        naration});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createLeaveApplicationAsync(string applicationNo, string employeeNumber, string reliever, string contactAddress, string naration) {
            this.createLeaveApplicationAsync(applicationNo, employeeNumber, reliever, contactAddress, naration, null);
        }
        
        /// <remarks/>
        public void createLeaveApplicationAsync(string applicationNo, string employeeNumber, string reliever, string contactAddress, string naration, object userState) {
            if ((this.createLeaveApplicationOperationCompleted == null)) {
                this.createLeaveApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateLeaveApplicationOperationCompleted);
            }
            this.InvokeAsync("createLeaveApplication", new object[] {
                        applicationNo,
                        employeeNumber,
                        reliever,
                        contactAddress,
                        naration}, this.createLeaveApplicationOperationCompleted, userState);
        }
        
        private void OncreateLeaveApplicationOperationCompleted(object arg) {
            if ((this.createLeaveApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createLeaveApplicationCompleted(this, new createLeaveApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:createSafariRequestEntitlemen" +
            "ts", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="createSafariRequestEntitlements_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string createSafariRequestEntitlements(string applicationNo, string entitlement, int quantity, decimal rate, string town) {
            object[] results = this.Invoke("createSafariRequestEntitlements", new object[] {
                        applicationNo,
                        entitlement,
                        quantity,
                        rate,
                        town});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createSafariRequestEntitlementsAsync(string applicationNo, string entitlement, int quantity, decimal rate, string town) {
            this.createSafariRequestEntitlementsAsync(applicationNo, entitlement, quantity, rate, town, null);
        }
        
        /// <remarks/>
        public void createSafariRequestEntitlementsAsync(string applicationNo, string entitlement, int quantity, decimal rate, string town, object userState) {
            if ((this.createSafariRequestEntitlementsOperationCompleted == null)) {
                this.createSafariRequestEntitlementsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateSafariRequestEntitlementsOperationCompleted);
            }
            this.InvokeAsync("createSafariRequestEntitlements", new object[] {
                        applicationNo,
                        entitlement,
                        quantity,
                        rate,
                        town}, this.createSafariRequestEntitlementsOperationCompleted, userState);
        }
        
        private void OncreateSafariRequestEntitlementsOperationCompleted(object arg) {
            if ((this.createSafariRequestEntitlementsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createSafariRequestEntitlementsCompleted(this, new createSafariRequestEntitlementsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:createSafariRequestHeader", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="createSafariRequestHeader_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string createSafariRequestHeader(string applicationNo, string employeeNumber, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime exptTravelDate, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime exptReturnDate, int modeOfTransPort, string functionCode, string budgetCode, string purpose) {
            object[] results = this.Invoke("createSafariRequestHeader", new object[] {
                        applicationNo,
                        employeeNumber,
                        exptTravelDate,
                        exptReturnDate,
                        modeOfTransPort,
                        functionCode,
                        budgetCode,
                        purpose});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createSafariRequestHeaderAsync(string applicationNo, string employeeNumber, System.DateTime exptTravelDate, System.DateTime exptReturnDate, int modeOfTransPort, string functionCode, string budgetCode, string purpose) {
            this.createSafariRequestHeaderAsync(applicationNo, employeeNumber, exptTravelDate, exptReturnDate, modeOfTransPort, functionCode, budgetCode, purpose, null);
        }
        
        /// <remarks/>
        public void createSafariRequestHeaderAsync(string applicationNo, string employeeNumber, System.DateTime exptTravelDate, System.DateTime exptReturnDate, int modeOfTransPort, string functionCode, string budgetCode, string purpose, object userState) {
            if ((this.createSafariRequestHeaderOperationCompleted == null)) {
                this.createSafariRequestHeaderOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateSafariRequestHeaderOperationCompleted);
            }
            this.InvokeAsync("createSafariRequestHeader", new object[] {
                        applicationNo,
                        employeeNumber,
                        exptTravelDate,
                        exptReturnDate,
                        modeOfTransPort,
                        functionCode,
                        budgetCode,
                        purpose}, this.createSafariRequestHeaderOperationCompleted, userState);
        }
        
        private void OncreateSafariRequestHeaderOperationCompleted(object arg) {
            if ((this.createSafariRequestHeaderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createSafariRequestHeaderCompleted(this, new createSafariRequestHeaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:createSafariRequestLines", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="createSafariRequestLines_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string createSafariRequestLines(string applicationNo, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime expseDate, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime returnDate, string travelFrom, string travelTo) {
            object[] results = this.Invoke("createSafariRequestLines", new object[] {
                        applicationNo,
                        expseDate,
                        returnDate,
                        travelFrom,
                        travelTo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createSafariRequestLinesAsync(string applicationNo, System.DateTime expseDate, System.DateTime returnDate, string travelFrom, string travelTo) {
            this.createSafariRequestLinesAsync(applicationNo, expseDate, returnDate, travelFrom, travelTo, null);
        }
        
        /// <remarks/>
        public void createSafariRequestLinesAsync(string applicationNo, System.DateTime expseDate, System.DateTime returnDate, string travelFrom, string travelTo, object userState) {
            if ((this.createSafariRequestLinesOperationCompleted == null)) {
                this.createSafariRequestLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateSafariRequestLinesOperationCompleted);
            }
            this.InvokeAsync("createSafariRequestLines", new object[] {
                        applicationNo,
                        expseDate,
                        returnDate,
                        travelFrom,
                        travelTo}, this.createSafariRequestLinesOperationCompleted, userState);
        }
        
        private void OncreateSafariRequestLinesOperationCompleted(object arg) {
            if ((this.createSafariRequestLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createSafariRequestLinesCompleted(this, new createSafariRequestLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:createStaffApplication", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="createStaffApplication_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string createStaffApplication(string applicationNo, string employeeNumber, string safariCode, string fundCode) {
            object[] results = this.Invoke("createStaffApplication", new object[] {
                        applicationNo,
                        employeeNumber,
                        safariCode,
                        fundCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createStaffApplicationAsync(string applicationNo, string employeeNumber, string safariCode, string fundCode) {
            this.createStaffApplicationAsync(applicationNo, employeeNumber, safariCode, fundCode, null);
        }
        
        /// <remarks/>
        public void createStaffApplicationAsync(string applicationNo, string employeeNumber, string safariCode, string fundCode, object userState) {
            if ((this.createStaffApplicationOperationCompleted == null)) {
                this.createStaffApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateStaffApplicationOperationCompleted);
            }
            this.InvokeAsync("createStaffApplication", new object[] {
                        applicationNo,
                        employeeNumber,
                        safariCode,
                        fundCode}, this.createStaffApplicationOperationCompleted, userState);
        }
        
        private void OncreateStaffApplicationOperationCompleted(object arg) {
            if ((this.createStaffApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createStaffApplicationCompleted(this, new createStaffApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:createStaffClaimApplicationLi" +
            "nes", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="createStaffClaimApplicationLines_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string createStaffClaimApplicationLines(string applicationNo, string claimType, int noOfDays, int noOfNights, int quantity, decimal rate, string reasonForClaim) {
            object[] results = this.Invoke("createStaffClaimApplicationLines", new object[] {
                        applicationNo,
                        claimType,
                        noOfDays,
                        noOfNights,
                        quantity,
                        rate,
                        reasonForClaim});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createStaffClaimApplicationLinesAsync(string applicationNo, string claimType, int noOfDays, int noOfNights, int quantity, decimal rate, string reasonForClaim) {
            this.createStaffClaimApplicationLinesAsync(applicationNo, claimType, noOfDays, noOfNights, quantity, rate, reasonForClaim, null);
        }
        
        /// <remarks/>
        public void createStaffClaimApplicationLinesAsync(string applicationNo, string claimType, int noOfDays, int noOfNights, int quantity, decimal rate, string reasonForClaim, object userState) {
            if ((this.createStaffClaimApplicationLinesOperationCompleted == null)) {
                this.createStaffClaimApplicationLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateStaffClaimApplicationLinesOperationCompleted);
            }
            this.InvokeAsync("createStaffClaimApplicationLines", new object[] {
                        applicationNo,
                        claimType,
                        noOfDays,
                        noOfNights,
                        quantity,
                        rate,
                        reasonForClaim}, this.createStaffClaimApplicationLinesOperationCompleted, userState);
        }
        
        private void OncreateStaffClaimApplicationLinesOperationCompleted(object arg) {
            if ((this.createStaffClaimApplicationLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createStaffClaimApplicationLinesCompleted(this, new createStaffClaimApplicationLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:createStoreRequisitionLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="createStoreRequisitionLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string createStoreRequisitionLine(string requisitionNo, string item, string location, int quantity) {
            object[] results = this.Invoke("createStoreRequisitionLine", new object[] {
                        requisitionNo,
                        item,
                        location,
                        quantity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createStoreRequisitionLineAsync(string requisitionNo, string item, string location, int quantity) {
            this.createStoreRequisitionLineAsync(requisitionNo, item, location, quantity, null);
        }
        
        /// <remarks/>
        public void createStoreRequisitionLineAsync(string requisitionNo, string item, string location, int quantity, object userState) {
            if ((this.createStoreRequisitionLineOperationCompleted == null)) {
                this.createStoreRequisitionLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateStoreRequisitionLineOperationCompleted);
            }
            this.InvokeAsync("createStoreRequisitionLine", new object[] {
                        requisitionNo,
                        item,
                        location,
                        quantity}, this.createStoreRequisitionLineOperationCompleted, userState);
        }
        
        private void OncreateStoreRequisitionLineOperationCompleted(object arg) {
            if ((this.createStoreRequisitionLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createStoreRequisitionLineCompleted(this, new createStoreRequisitionLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:createStoreRequisition", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="createStoreRequisition_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string createStoreRequisition(string employeeNo, string requisitionNo, string description, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime requiredDate) {
            object[] results = this.Invoke("createStoreRequisition", new object[] {
                        employeeNo,
                        requisitionNo,
                        description,
                        requiredDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createStoreRequisitionAsync(string employeeNo, string requisitionNo, string description, System.DateTime requiredDate) {
            this.createStoreRequisitionAsync(employeeNo, requisitionNo, description, requiredDate, null);
        }
        
        /// <remarks/>
        public void createStoreRequisitionAsync(string employeeNo, string requisitionNo, string description, System.DateTime requiredDate, object userState) {
            if ((this.createStoreRequisitionOperationCompleted == null)) {
                this.createStoreRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateStoreRequisitionOperationCompleted);
            }
            this.InvokeAsync("createStoreRequisition", new object[] {
                        employeeNo,
                        requisitionNo,
                        description,
                        requiredDate}, this.createStoreRequisitionOperationCompleted, userState);
        }
        
        private void OncreateStoreRequisitionOperationCompleted(object arg) {
            if ((this.createStoreRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createStoreRequisitionCompleted(this, new createStoreRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:editLeaveApplicationLines", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="editLeaveApplicationLines_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string editLeaveApplicationLines(string applicationNo, int lineNo, string leaveType, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateStart, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateEnd) {
            object[] results = this.Invoke("editLeaveApplicationLines", new object[] {
                        applicationNo,
                        lineNo,
                        leaveType,
                        dateStart,
                        dateEnd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void editLeaveApplicationLinesAsync(string applicationNo, int lineNo, string leaveType, System.DateTime dateStart, System.DateTime dateEnd) {
            this.editLeaveApplicationLinesAsync(applicationNo, lineNo, leaveType, dateStart, dateEnd, null);
        }
        
        /// <remarks/>
        public void editLeaveApplicationLinesAsync(string applicationNo, int lineNo, string leaveType, System.DateTime dateStart, System.DateTime dateEnd, object userState) {
            if ((this.editLeaveApplicationLinesOperationCompleted == null)) {
                this.editLeaveApplicationLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditLeaveApplicationLinesOperationCompleted);
            }
            this.InvokeAsync("editLeaveApplicationLines", new object[] {
                        applicationNo,
                        lineNo,
                        leaveType,
                        dateStart,
                        dateEnd}, this.editLeaveApplicationLinesOperationCompleted, userState);
        }
        
        private void OneditLeaveApplicationLinesOperationCompleted(object arg) {
            if ((this.editLeaveApplicationLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editLeaveApplicationLinesCompleted(this, new editLeaveApplicationLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:fnGetEmployeeDetail", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="fnGetEmployeeDetail_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string fnGetEmployeeDetail(string empNumber) {
            object[] results = this.Invoke("fnGetEmployeeDetail", new object[] {
                        empNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fnGetEmployeeDetailAsync(string empNumber) {
            this.fnGetEmployeeDetailAsync(empNumber, null);
        }
        
        /// <remarks/>
        public void fnGetEmployeeDetailAsync(string empNumber, object userState) {
            if ((this.fnGetEmployeeDetailOperationCompleted == null)) {
                this.fnGetEmployeeDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnGetEmployeeDetailOperationCompleted);
            }
            this.InvokeAsync("fnGetEmployeeDetail", new object[] {
                        empNumber}, this.fnGetEmployeeDetailOperationCompleted, userState);
        }
        
        private void OnfnGetEmployeeDetailOperationCompleted(object arg) {
            if ((this.fnGetEmployeeDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnGetEmployeeDetailCompleted(this, new fnGetEmployeeDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:fnStoreRequisitionLines", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="fnStoreRequisitionLines_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string fnStoreRequisitionLines(string appNo) {
            object[] results = this.Invoke("fnStoreRequisitionLines", new object[] {
                        appNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fnStoreRequisitionLinesAsync(string appNo) {
            this.fnStoreRequisitionLinesAsync(appNo, null);
        }
        
        /// <remarks/>
        public void fnStoreRequisitionLinesAsync(string appNo, object userState) {
            if ((this.fnStoreRequisitionLinesOperationCompleted == null)) {
                this.fnStoreRequisitionLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnStoreRequisitionLinesOperationCompleted);
            }
            this.InvokeAsync("fnStoreRequisitionLines", new object[] {
                        appNo}, this.fnStoreRequisitionLinesOperationCompleted, userState);
        }
        
        private void OnfnStoreRequisitionLinesOperationCompleted(object arg) {
            if ((this.fnStoreRequisitionLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnStoreRequisitionLinesCompleted(this, new fnStoreRequisitionLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:generateP9", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="generateP9_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string generateP9(string employeeNumber, int year) {
            object[] results = this.Invoke("generateP9", new object[] {
                        employeeNumber,
                        year});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void generateP9Async(string employeeNumber, int year) {
            this.generateP9Async(employeeNumber, year, null);
        }
        
        /// <remarks/>
        public void generateP9Async(string employeeNumber, int year, object userState) {
            if ((this.generateP9OperationCompleted == null)) {
                this.generateP9OperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerateP9OperationCompleted);
            }
            this.InvokeAsync("generateP9", new object[] {
                        employeeNumber,
                        year}, this.generateP9OperationCompleted, userState);
        }
        
        private void OngenerateP9OperationCompleted(object arg) {
            if ((this.generateP9Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generateP9Completed(this, new generateP9CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:generatePayslip", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="generatePayslip_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string generatePayslip(string employeeNumber, int year, int month) {
            object[] results = this.Invoke("generatePayslip", new object[] {
                        employeeNumber,
                        year,
                        month});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void generatePayslipAsync(string employeeNumber, int year, int month) {
            this.generatePayslipAsync(employeeNumber, year, month, null);
        }
        
        /// <remarks/>
        public void generatePayslipAsync(string employeeNumber, int year, int month, object userState) {
            if ((this.generatePayslipOperationCompleted == null)) {
                this.generatePayslipOperationCompleted = new System.Threading.SendOrPostCallback(this.OngeneratePayslipOperationCompleted);
            }
            this.InvokeAsync("generatePayslip", new object[] {
                        employeeNumber,
                        year,
                        month}, this.generatePayslipOperationCompleted, userState);
        }
        
        private void OngeneratePayslipOperationCompleted(object arg) {
            if ((this.generatePayslipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generatePayslipCompleted(this, new generatePayslipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:sendLeaveApplicationApproval", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="sendLeaveApplicationApproval_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string sendLeaveApplicationApproval(string applicationNo) {
            object[] results = this.Invoke("sendLeaveApplicationApproval", new object[] {
                        applicationNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendLeaveApplicationApprovalAsync(string applicationNo) {
            this.sendLeaveApplicationApprovalAsync(applicationNo, null);
        }
        
        /// <remarks/>
        public void sendLeaveApplicationApprovalAsync(string applicationNo, object userState) {
            if ((this.sendLeaveApplicationApprovalOperationCompleted == null)) {
                this.sendLeaveApplicationApprovalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendLeaveApplicationApprovalOperationCompleted);
            }
            this.InvokeAsync("sendLeaveApplicationApproval", new object[] {
                        applicationNo}, this.sendLeaveApplicationApprovalOperationCompleted, userState);
        }
        
        private void OnsendLeaveApplicationApprovalOperationCompleted(object arg) {
            if ((this.sendLeaveApplicationApprovalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendLeaveApplicationApprovalCompleted(this, new sendLeaveApplicationApprovalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:sendSafariRequestApplicationA" +
            "pproval", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="sendSafariRequestApplicationApproval_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string sendSafariRequestApplicationApproval(string applicationNo) {
            object[] results = this.Invoke("sendSafariRequestApplicationApproval", new object[] {
                        applicationNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendSafariRequestApplicationApprovalAsync(string applicationNo) {
            this.sendSafariRequestApplicationApprovalAsync(applicationNo, null);
        }
        
        /// <remarks/>
        public void sendSafariRequestApplicationApprovalAsync(string applicationNo, object userState) {
            if ((this.sendSafariRequestApplicationApprovalOperationCompleted == null)) {
                this.sendSafariRequestApplicationApprovalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSafariRequestApplicationApprovalOperationCompleted);
            }
            this.InvokeAsync("sendSafariRequestApplicationApproval", new object[] {
                        applicationNo}, this.sendSafariRequestApplicationApprovalOperationCompleted, userState);
        }
        
        private void OnsendSafariRequestApplicationApprovalOperationCompleted(object arg) {
            if ((this.sendSafariRequestApplicationApprovalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSafariRequestApplicationApprovalCompleted(this, new sendSafariRequestApplicationApprovalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/NewHrPortal:sendStaffClaimApplicationAppr" +
            "oval", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", ResponseElementName="sendStaffClaimApplicationApproval_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/NewHrPortal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string sendStaffClaimApplicationApproval(string applicationNo) {
            object[] results = this.Invoke("sendStaffClaimApplicationApproval", new object[] {
                        applicationNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendStaffClaimApplicationApprovalAsync(string applicationNo) {
            this.sendStaffClaimApplicationApprovalAsync(applicationNo, null);
        }
        
        /// <remarks/>
        public void sendStaffClaimApplicationApprovalAsync(string applicationNo, object userState) {
            if ((this.sendStaffClaimApplicationApprovalOperationCompleted == null)) {
                this.sendStaffClaimApplicationApprovalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendStaffClaimApplicationApprovalOperationCompleted);
            }
            this.InvokeAsync("sendStaffClaimApplicationApproval", new object[] {
                        applicationNo}, this.sendStaffClaimApplicationApprovalOperationCompleted, userState);
        }
        
        private void OnsendStaffClaimApplicationApprovalOperationCompleted(object arg) {
            if ((this.sendStaffClaimApplicationApprovalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendStaffClaimApplicationApprovalCompleted(this, new sendStaffClaimApplicationApprovalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void changePasswordCompletedEventHandler(object sender, changePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void createLeaveApplicationLinesCompletedEventHandler(object sender, createLeaveApplicationLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createLeaveApplicationLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createLeaveApplicationLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void createLeaveApplicationCompletedEventHandler(object sender, createLeaveApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createLeaveApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createLeaveApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void createSafariRequestEntitlementsCompletedEventHandler(object sender, createSafariRequestEntitlementsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createSafariRequestEntitlementsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createSafariRequestEntitlementsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void createSafariRequestHeaderCompletedEventHandler(object sender, createSafariRequestHeaderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createSafariRequestHeaderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createSafariRequestHeaderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void createSafariRequestLinesCompletedEventHandler(object sender, createSafariRequestLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createSafariRequestLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createSafariRequestLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void createStaffApplicationCompletedEventHandler(object sender, createStaffApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createStaffApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createStaffApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void createStaffClaimApplicationLinesCompletedEventHandler(object sender, createStaffClaimApplicationLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createStaffClaimApplicationLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createStaffClaimApplicationLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void createStoreRequisitionLineCompletedEventHandler(object sender, createStoreRequisitionLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createStoreRequisitionLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createStoreRequisitionLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void createStoreRequisitionCompletedEventHandler(object sender, createStoreRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createStoreRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createStoreRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void editLeaveApplicationLinesCompletedEventHandler(object sender, editLeaveApplicationLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editLeaveApplicationLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editLeaveApplicationLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void fnGetEmployeeDetailCompletedEventHandler(object sender, fnGetEmployeeDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnGetEmployeeDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnGetEmployeeDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void fnStoreRequisitionLinesCompletedEventHandler(object sender, fnStoreRequisitionLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnStoreRequisitionLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnStoreRequisitionLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void generateP9CompletedEventHandler(object sender, generateP9CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generateP9CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generateP9CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void generatePayslipCompletedEventHandler(object sender, generatePayslipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generatePayslipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generatePayslipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void sendLeaveApplicationApprovalCompletedEventHandler(object sender, sendLeaveApplicationApprovalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendLeaveApplicationApprovalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendLeaveApplicationApprovalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void sendSafariRequestApplicationApprovalCompletedEventHandler(object sender, sendSafariRequestApplicationApprovalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSafariRequestApplicationApprovalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendSafariRequestApplicationApprovalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void sendStaffClaimApplicationApprovalCompletedEventHandler(object sender, sendStaffClaimApplicationApprovalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendStaffClaimApplicationApprovalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendStaffClaimApplicationApprovalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591